### ISSUE TITLE
organize jimber related components

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/home#12]
make sure all jimber related components are understood, documentable, buildable and in repo's where we are also admin.

exception the jimber code itself, but there too we need to make sure its all buildable & understood

> have docker compose scripts for everything & good enough documentation

**Comment by lennertdefauw** [comment]
##  Freeflow:
### Main repository: 
twin aydo: https://github.com/threefoldtech/twin_aydo

### Related repositories: 
meetings: https://github.com/freeflowuniverse/freeflow_kutana_ui
browser: https://github.com/JimberSoftware/browser

### Deprecated repositories:
digitaltwin-lib: https://github.com/threefoldtech/digitaltwin-lib DEPRECATED
digitaltwin-spawner: https://github.com/threefoldtech/digitaltwin_spawner DEPRECATED
digitaltwin-dev https://github.com/jimbertools/digitaltwin-dev DEPRECATED

## ThreeFold Login SDK
threefold-login-js-sdk: https://github.com/threefoldtech/threefold-login-js-sdk


## PKID
### Main repository: 
pkid: https://github.com/threefoldtech/pkid

### Related repositories:
pkid_nest: https://github.com/threefoldtech/pkid_nest
pkid-node-client: https://github.com/threefoldtech/pkid-node-client
pkid_python_sdk: https://github.com/threefoldtech/pkid_python_sdk
threefold_login_pkid_example: https://github.com/threefoldtech/threefold_login_pkid_example

## Demos
demo-chains-js: https://github.com/threefoldtech/demo-chains-js


## ThreeFold Connect
### Main repository:
threefold_connect: https://github.com/threefoldtech/threefold_connect

### Related repositories
threefold_connect_news: https://github.com/threefoldtech/threefold_connect_news
flutter-pkid-client: https://github.com/threefoldtech/flutter-pkid-client
openkyc: https://github.com/threefoldtech/openkyc


## Wallet
### Main repository: 
wallet-next: https://github.com/threefoldtech/wallet-next

### Related repositories:
simple-bip39 https://github.com/jimbertools/simple-bip39
stellar-crypto https://github.com/JimberSoftware/stellar-crypto

### Deprecated repositories: 
threefold_wallet: https://github.com/threefoldtech/threefold_wallet DEPRECATED


## Planetary network:
### Related repositories: 
yggdrasil_flutter: https://github.com/threefoldtech/yggdrasil_flutter
planetary_network: https://github.com/threefoldtech/planetary_network

## Misc
freeflowdevenv: https://github.com/threefoldtech/freeflowdevenv

**Comment by despiegk** [comment]
lots of things still to fix
https://github.com/freeflowuniverse/home/blob/master/docs/code_locations.md
