### ISSUE TITLE
organize ourverse related components

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/home#13]
purpose is we learn how we can work together and help the metaverse team if needed to use github well in proper way

* where is code of the metaverse (prob on their own account)
* how to build (make sure we have good build instructions)
* what is there? whats not?
* gather all architecture info, ...
* understand what is what and what does it do
* where are prio's managed? are things on github, is there account, ...
* document all in a new repo called ourverse (use mdbook see books in foundation account)
* make team for the ourverse (metaverse) team, give them access to this private repo and this account
* we need to have admin access to their github account too

**Comment by xmonader** [comment]
I'll update their repo today with the information needed

**Comment by xmonader** [comment]
https://github.com/freeflowuniverse/ourverse added the the current info i have from the team missing the operations guide (being worked on)
