### ISSUE TITLE
create wiki for vlang 

### ISSUE THREAD

**Issue by rkhamis** [freeflowuniverse/home#2]
make a wiki (using our publ tools) porting https://github.com/vlang/v/blob/master/doc/docs.md#strings

wiki should have:
 - page per relevant section
 - sidebar with all topics

**Comment by weynandkuijpers** [comment]
- [x] create info_vlang repo
- [x] created scripts that takes the original vlang doc file and cuts it into chapters / sections. 
- [ ] optimize and correct script mistakes
- [ ] check automatic `sidebar.md` file creation
- [ ] check overall linkage and readability (maybe add `next` and `previous` page navigation

**Comment by weynandkuijpers** [comment]
repo is here: https://github.com/threefoldfoundation/info_vlang

**Comment by rkhamis** [comment]
done
