### ISSUE TITLE
all in one zola/mdbook runner

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/home#23]
do

* vrun  /root/code/github/despiegk/env_web/ourworld/ourworld_install.v

see

* ssh -A root@ourworld.tf. (this is the server where all happens)
* all is already there, crystallib v, ...

add all known mdbooks

* https://github.com/ourworldventures/ourworld_books
* https://ourworldfreezone.github.io/info_freezone/intro/intro_readme.html
* https://github.com/threefoldfoundation/books

todo

* add some info in manual for crystallib
* do same as mdbook but for zola
  * the idea is we can also pull in parts of websites in one mother website e.g. for blogs, just like we do for wiki
  * see installer & osal, already prepared zola (just copy paste mainly of mdbook and rename)
* add all websites to the installer, and make sure we watch over both (will need to make a change to make both happen)
* if any of our websites still not on zola, lets migrate now
* create a hosts file for debug so we can test easily locally on top of e.g. caddy (see hostfile sal)
* add to 3script like mdbook
* add to hero like mdbook

remark

* the doctree (knowledtree) cannot be used yet, in middle of huge refactoring on markdown and how we do the actions
* we know today its only usable by us, but once actions are working again it will be easy to change

**Comment by despiegk** [comment]
is on development_db for now

**Comment by despiegk** [comment]
github/freeflowuniverse/crystallib/crystallib/osal/hostsfile/hostsfile.v 
is broken too, also need fix, so we can generate hostfile as well

**Comment by timurgordon** [comment]
We can work locally on this, made the necessary fixes as the remote server was inaccessible @samaradel @sasha-astiadi . 

we need to add the known mdbooks mentioned in the task. to do so, we need to add code that imports and generates books (see `env_web/ourworld/books/datacenter.v`)

we can then run the installer with `v -cg -enable-globals run ~code/github/despiegk/env_web/ourworld/ourworld_install.v`

this will generate the books in `${root_dir}/mdbooks`
root_dir is specified in `~code/github/despiegk/env_web/ourworld/ourworld_install.v` line 16, and is default `/var`
in MacOS `/var` requires permissions, so replace with `tmp` 

then we have to make sure that all summaries are correct and books are being generated correctly.

**Comment by samaradel** [comment]
@sasha-astiadi please confirm if we have other books.
@timurgordon I need access too.

**Comment by timurgordon** [comment]
> @sasha-astiadi please confirm if we have other books.
> @timurgordon I need access too.

added your ssh key, we're working from the remote server. `root@info.ourworld.tf`

**Comment by samaradel** [comment]
> root@info.ourworld.tf

it needs password
![image](https://github.com/freeflowuniverse/home/assets/11662805/6c0cf28c-69d7-413c-912f-2ed1ad686440)

**Comment by timurgordon** [comment]
Getting this error because I also have Zola installed in another path via brew: 

![Image](https://github.com/freeflowuniverse/home/assets/31495328/e2128792-4867-4ad1-9640-8ab75a46fac1)

Is it ok if we symlink to `~/hero/bin` in such cases in macOS? Would be implemented in `crystallib/osal/cmds_add.v` `fn cmd_add`
