### ISSUE TITLE
freeflow twin release 1.7

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/home#7]
## checks

* [ ] installs in kubernetes or flist based
  * [ ] well documented docker build files/scripts
* [ ] good enough experience to be alternative to early dropbox, gdrive, whatsapp
* [ ] good enough quantum filemanager
  * [ ] good enough viewers/editors
    * [ ] pdf viewer embedded (new tab, as well as integrated (which means inside the working space))
    * [ ] text formats (code, md, ...) with editor if possible, worst case better viewer (integrated)
    * [ ] office docs editor (only full screen)
    * [ ] video viewer, with streaming support, no need to fully download (separate tab, integrated)
    * [ ] audio listener (separate tab, integrated)
    * [ ] photo viewer / gallery if directory (separate tab, integrated)
  * [ ] share file/folder based on url
  * [ ] allow chat to send file/folder/image/video from quantum to be send
  * [ ] allow people to deploy their own doceditor in location of choice, allow config of install to point to their doceditor server
* [ ] kutana good enough
  * allow people to deploy their own MTU, allow config for deployment to point to their installed MTU
  * support if network breaks, now the full session is lost, no possibility to reconnect
  * [ ] allow MTU re-coding (optional) so not everyone goes to worst quality (only works if they deployed their own MTU)
    * [ ] have a low quality and high quality mode, participants get the high or low depending their line, but can be mixed
* [ ] code mgmt good enough
  * [ ] all code in right location see other stories/tasks

> complete this list

**Comment by despiegk** [comment]
where can we see the detailed of what is being worked on

**Comment by despiegk** [comment]
## per server deployed

- browser engine
- docu server
- mtu for video conference

**Comment by despiegk** [comment]
Uhuru version: https://github.com/threefoldtech/twin_aydo/projects/12

- Bug fixes
- Fixing onlyoffice stability
- Improving unstable internet support by a lot.
- stability for usage more than 2 people

**Comment by despiegk** [comment]
make sure all is well enough documented
see https://github.com/threefoldtech/home/issues/1309 for history

**Comment by ken-de-moor** [comment]
Current state : V1.7 in testing, actual projects board are at https://github.com/threefoldtech/twin_aydo/projects?type=classic

Documentation and repo remaining is still in progress.

**Comment by xmonader** [comment]
deployment issue https://github.com/threefoldtech/home/issues/1301
